### ISSUE TITLE
November Task List - Things I need to get done in November that can not drag out.

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/slate#401]
Now that I have some time to redirect, it's time to focus on some critical tasks for the success of Slate. This list is not part of the shared task list that the Slate team uses, but enables a lot of new features and improvements to Slate.

### Buckets Cycling

Buckets cycling is a concept that allows us to provide 50GB+ of free storage to users of Slate without having to have it within a single bucket. This is because we don't know when the 4GB bucket limit will be lifted.

- [ ] Implement bucket cycling.
- [ ] Update marketing to explain the nuance.

### Account Verification

We need to implement OAuth as well as e-mail verification to enable

* Filecoin features
* API key generation
* 50GB (allow beyond 4GB that we offer pre-verfiication)

- [ ] E-mail verification implemented
- [ ] Github authentication implemented
- [ ] Sign in with Slate implemented (https://github.com/filecoin-project/slate/issues/390)
- [ ] Verify this satisfies the MetaMask requirement (https://github.com/filecoin-project/slate/issues/300) (cc: @nicola)
- [ ] Update marketing to explain the nuance for accounts that are verified

### LibP2P Authentication for Decentralization

To support our decentralized story and offline story, we will implement a version of Slate that people can use in the web that does not require authentication. We won't use local storage, rather we will setup the pieces that allow for a beaker browser authentication where the user keeps the auth in their own browser.

- [ ] Implement LibP2P Authentication that disappears on refresh.

### Developer Plugins, How do I get my App into Slate!?

- [ ] Implement the first SDK example (https://github.com/filecoin-project/slate/issues/115)

### Other meaningful features

- https://github.com/filecoin-project/slate/issues/395 (Experience making a miner, then provide "Create a Miner through Slate")
- https://github.com/filecoin-project/slate/issues/382 (Simplify Miner Selection)

### Bugs or things I need to test again

- https://github.com/filecoin-project/slate/issues/342 (IPFS companion incompatibility)
- https://github.com/filecoin-project/slate/issues/234 (Support e-mail verification so @tarafanlin can retrieve an account)
- https://github.com/filecoin-project/slate/issues/203 (Verify that Sunday checklist for PDF issues + usability issues and API issues is finished)

**Comment by jimmylee** [comment]
- [ ] API: Whenever someone uploads a Slate object via the API, allow them to add query parameters for certain fields.
- [ ] API: Whenever someone queries for a slate, let them get a slate by slate name.
- [ ] PDFS: Can't read PDFS on mobile.

**Comment by jimmylee** [comment]
https://github.com/filecoin-project/slate/issues/461
