### ISSUE TITLE
Multi file download

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#588]
# Purpose

- Right now you can only download one file at a time
- Would like to be able to select multiple files then download them
- And add a button to download a whole slate

# Deliverable

- Will need to zip the files first then download it

**Comment by Aminejvm** [comment]
I'll work on this feature 🕵️‍♂️

**Comment by Aminejvm** [comment]
This improvement should allow users to download selected items and entires slates as a zip file. I explored two solutions so far

- **On the client side**

    We compress the files on the client and then create an object url which will trigger the download, unfortunately the object can only contain 2048 characters

- **On the backend side**

    I started by trying to send the files urls and names to the backend, and we do the compression on the backend using streams, after that we send the zip file to the client. Unfortunately we can't trigger a file download with a POST request.

    My suggested solution is we should have two endpoint`/api/download/create-zip-token` and `/api/download/download-by-token`. (Dropbox uses something similar to this 🤫)

    - `/api/download/create-zip-token` (POST request)

        We would use this request to send files URLs and names and stored them in the backend with a token and return that token

    - `/api/download/download-by-token` (GET request)

        We would use the token we got from the prior request to get the metadata we need, then we compress the files and return the file to the client which will trigger a download

    - In the frontend we use an `iframe` to trigger the download
    - For errors handling in the frontend, if an error happens in the `download-by-token` request, we will send an html page with the following script which sends an error message to the parent, we'll listen for this event on the frontend and clear it when the iframe load

    ```jsx
    <script>
       parent.postMessage('SLATE_DOWNLOAD_ERROR','${SLATE_ORIGIN_HERE}');
    </script>
    ```

          

## Tasks

---

- [x]  Download All selected files
- [x]  Download a whole a slate
- [x]  Sync with @Haris Butt on the design
- [x]  Explore frontend and backend solutions
    - [x]  Frontend download
        - [x]  Download all the files
        - [x]  Zip the downloaded files
        - [ ]  handle unity games edge case
        - [x]  handle errors
        - [ ]  Handle download state
    - [x]  Backend download
        - [x]  create an endpoint where it sends files metadata and get a token
        - [x]  create an endpoint that consumes that token
        - [x]  create a stream where we download and zip the files
        - [x]  handle unity games edge case
        - [x]  handle errors
        - [x]  Find better way to store tokens ( we use REDIS now)
        - [x]  Handle errors

## Notes

---

Both solutions has pros and cons

### **Frontend download**

Pros

- Faster downloads for smaller files
- Less complexity

Cons

- Files are stored in the user's memory before zipping
- We have to handle the download state

### **Backend download**

Pros

- More efficient on the user's memory
- Download state is handled by the browser

Cons

- A bit slower than the frontend solution
- 2 server trips
