### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#665]
### Links T  Jason Leyser
* Extension Github: [https://github.com/jasonleyser/slate-for-chrome-v2-prototype](https://github.com/jasonleyser/slate-for-chrome-v2-prototype/issues)
* Design File: [https://www.figma.com/file/IF48S6bNTTgKJujwm9LgfT/Chrome-Extension-V2?node-id=171%3A10](https://www.figma.com/file/IF48S6bNTTgKJujwm9LgfT/Chrome-Extension-V2?node-id=171%3A10)
* Chrome Store Page: [https://chrome.google.com/webstore/detail/slate/gloembacbehhbfbkcfjmloikeeaebnoc](https://chrome.google.com/webstore/detail/slate/gloembacbehhbfbkcfjmloikeeaebnoc)
* Tweets:

Sync Feb 23, 2021 

* Planning on sharing Mar 5, 2021
* Use the extension to get the community involved and bring them into the Slate ecosystem
* What' shipping
  * Revamped extension: Totally new experience that extends Slate web client to be with you anywhere you are on the web
  * Works for images currently — audio and video will be introduced later on (can use this as a way to get the community involved.
* Need to work on the database structure to tie in the API
* Uploading UI is being worked on, main extension UI is setup
* Reviewed the upload history UI and made some quick edits

Sync Mar 2, 2021 1:00 PM 

[codebase manual](https://www.notion.so/codebase-manual-48784f692be5474bafa2a91313bb4ce4)

* [x]  firefox support
* [x]  remaining work log
* [x]  walk through codebase structure

**Todo**

* [x]  file path
* [ ]  svg color changes
* [x]  the weird array bug
* [ ]  fix typography
* [x]  innerHTML inside another innerHTML

### Todo
* [ ]  New chrome store assets and description
* [ ]  We should make a new page for the extension on the slate website
* [ ]  Social assets — record a demo to share the new extension in action
* [ ]  The actual extension
* [ ]  Blog post/writeup on the extension/Slate API
* [ ]  Firefox support

┆Issue is synchronized with this [Notion page](https://www.notion.so/Chrome-extension-68a685c66a094366b56698a45e207c46) by [Unito](https://www.unito.io)
