### ISSUE TITLE
NFT support exploration

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#668]
Our goal from this exploration is to make Slate a place where people can showcase their NFTs. The exploration has three main steps, viz; getting the user ethereum address, then use that address to store all their NFTs on Slate, and lastly find a way to verify and update those NFTs ownership.

## Tasks
* [ ]  Showing the badging for NFTs
* [ ]  Object Card details
* [ ]  What do we show inside the carousel view

### Auth
We're using Metamask wallet to get the user ethereum address. The process is straight forward that we should handle a few states. One question we had was about what to do in a case where the user has multiple accounts on the wallet. From our research what OpenSea does is to just log you on with your last ethereum account. [See images below]

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0438157a-e8ac-4563-890e-56d622532e10/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/0438157a-e8ac-4563-890e-56d622532e10/Untitled.png)

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/3c311b13-a7ba-431a-8799-20d3944eb497/Screen!UNITO-UNDERSCORE!Shot!UNITO-UNDERSCORE!2021-02-25!UNITO-UNDERSCORE!at!UNITO-UNDERSCORE!7.40.38!UNITO-UNDERSCORE!PM.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/3c311b13-a7ba-431a-8799-20d3944eb497/Screen_Shot_2021-02-25_at_7.40.38_PM.png)

After that, it should be easy to just add a field (e.g. `eth_address`) to the Slate user object.

### Storing NFT(s) on Slate
Once we get the `eth_address`, we can store any particular asset(s) associated with the user as the user may choose. 

In the case of storing a single NFT asset, we can use the following endpoint from OpenSea to store the asset on Slate by using the `token_id(s)` that the user will have to provide.

```jsx
https://api.opensea.io/api/v1/assets?token_ids=${array_of_asset_token_ids}
```

In the case of storing all assets associated with an `eth_address`, we can use the following OpenSea API endpoint.

```jsx
https://api.opensea.io/api/v1/assets?owner=${owner_address}
```

We can use the response we get from OpenSea to upload all the NFTs to Slate with its metadata in both cases.

### Verifying Ownership of NFT
From our research, we found that the OpenSea api returns an `owner` data in the metadata for a specific asset when the asset endpoints are called.

```jsx
https://api.opensea.io/api/v1/asset/${asset_address}
https://api.opensea.io/api/v1/assets?${other_params}
```

For this reason, we can verify whether the Slate user owns the NFT asset(s) that they want to upload on Slate by comparing the `eth_address` that Metamask returns when the user authenticates with Metamask in Slate with the `eth_address` in the `owner` object that the OpenSea API returns as part of the metadata.

(sidenote: few endpoints (/event, /accounts, /asset_contracts) from OpenSea will be deprecated in March and they [suggested](https://docs.opensea.io/page/partial-api-deprecation-notice) this platform as replacement [thegraph.com](https://thegraph.com/)  )

### Question
**What is the most efficient way to update ownership of NFTs assets stored on Slate?**
Since the ownership of an NFT can change at anytime through sale or transfer, we want to explore ways by which we can keep the NFT stored on slate updated. In our thinking, we do not think that it will be right for a user who has sold or transferred an asset to be able to keep them on their slate. Once ownership changes, we need to remove it from that persons slate. 

To do this, we're thinking that we can verify the ownership of an asset each time someone fetch it and check if it is still owned by the creator of the slate. We're not sure how efficient this approach it's going be. We are open to ideas on this point. 

### The Graph
The Graph is a decentralized protocol that makes it easy to index and query data from the blockchains using subgraphs. A Subgraph is a way for us to defines which data the Graph will index from Ethereum. There is many already built subgraphs
[https://thegraph.com/explorer/subgraph/knownorigin/known-origin](https://thegraph.com/explorer/subgraph/knownorigin/known-origin)

[https://thegraph.com/explorer/subgraph/f8n/fnd](https://thegraph.com/explorer/subgraph/f8n/fnd)

[https://thegraph.com/explorer/subgraph/sashimiproject/nft](https://thegraph.com/explorer/subgraph/sashimiproject/nft)

[https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph](https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph)

[https://thegraph.com/explorer/subgraph/frostiq/cryptomedia](https://thegraph.com/explorer/subgraph/frostiq/cryptomedia)

Here is for example on how to query all Jim's NFTs  from foundation subgraph

```jsx
{
  account(id: "0xaff777d14dd576144efe700b83485ca64388e725") {
    nfts {
      id
      name
      description
      image
      tokenIPFSPath
      owner {
        id
      }
    }
  }
}
```

And this is how to query metadata related to an NFT

```jsx
{
  nft(id: "0x3b3ee1931dc30c1957379fac9aba94d1c48a5405-355") {
    name
    tokenIPFSPath
    owner {
      id
    }
  }
}
```

┆Issue is synchronized with this [Notion page](https://www.notion.so/NFT-support-exploration-4355c68a3db24fcfa2d0243cf7ba9553) by [Unito](https://www.unito.io)
