### ISSUE TITLE
Improve API docs

### ISSUE THREAD

**Issue by martinalong** [filecoin-project/slate#669]
## Summary

---

- There should be some kind of selection menu to show better examples in different languages, and it should either be in a sidebar link to a documentation page or in small dropdowns on the same page (or both!)

## Tasks

---

- [ ]  Add documentation/examples for API in python w/flask micro-framework
- [ ]  Add documentation/examples for API in go w/gin-gonic, echo, or net/http
- [ ]  Add any other languages you can think of to this list, feel free to assign yourself to this task

## Notes

---

- As of now, the API page for slate only has examples in Node.js and isn't organized in any particular fashion/doesn't demonstrate any particular task that can be accomplished with the API
- The API is pretty cool, with potential to be even more cool, but we don't really demonstrate that
